#!/bin/bash
renice -n -10 -p $$ > /dev/null
########################################################################
############ DO NOT TOUCH ##############################################
############ bitrate modified ##########################################
########################################################################
bitrate_35=(0 c0f21623)
bitrate_40=(0 c0f26223)
bitrate_45=(0 c0f2ae23)
bitrate_50=(0 c0f2fa23)
bitrate_55=(0 c0f24733)
bitrate_60=(0 c0f29333)
bitrate_65=(0 c0f2df33)
bitrate_70=(0 c0f22c43)
bitrate_75=(0 c0f27843)
bitrate_80=(0 c0f2c443)
bitrate_85=(0 c0f21053)
bitrate_90=(0 c0f25d53)
bitrate_95=(0 c0f2a953)
bitrate_100=(0 c0f2f553)
bitrate_110=(0 c0f28e63)
bitrate_120=(0 c0f22773)
bitrate_130=(0 c0f2bf73)
bitrate_140=(0 c0f6583)
bitrate_150=(0 c0f6f03)
bitrate_160=(0 c0f68913)
bitrate_170=(0 c0f62123)
bitrate_180=(0 c0f6ba23)
bitrate_190=(0 c0f65333)
bitrate_200=(0 c0f6eb33)
bitrate_210=(0 c0f68443)
bitrate_220=(0 c0f61c53)
bitrate_230=(0 c0f6b553)
bitrate_240=(0 c0f64e63)
bitrate_250=(0 c0f6e663)
bitrate_260=(0 c0f67f73)
bitrate_270=(0 c1f2173)
bitrate_280=(0 c1f2b03)
bitrate_290=(0 c1f24913)
bitrate_300=(0 c1f2e113)
bitrate_310=(0 c1f27a23)
bitrate_320=(0 c1f21233)
bitrate_400=(0 c1f2d773)
########################################################################
############ DO NOT TOUCH ##############################################
############ bitrate NX500 PRO #########################################
########################################################################
bitrate_nx500pro_35=(0 c0f21620)
bitrate_nx500pro_40=(0 c0f26220)
bitrate_nx500pro_45=(0 c0f2ae20)
bitrate_nx500pro_50=(0 c0f2fa20)
bitrate_nx500pro_55=(0 c0f24730)
bitrate_nx500pro_60=(0 c0f29330)
bitrate_nx500pro_65=(0 c0f2df30)
bitrate_nx500pro_70=(0 c0f22c40)
bitrate_nx500pro_75=(0 c0f27840)
bitrate_nx500pro_80=(0 c0f2c440)
bitrate_nx500pro_85=(0 c0f21050)
bitrate_nx500pro_90=(0 c0f25d50)
bitrate_nx500pro_95=(0 c0f2a950)
bitrate_nx500pro_100=(0 c0f2f550)
bitrate_nx500pro_110=(0 c0f28e60)
bitrate_nx500pro_120=(0 c0f22770)
bitrate_nx500pro_130=(0 c0f2bf70)
bitrate_nx500pro_140=(0 c0f6580)
bitrate_nx500pro_150=(0 c0f6f00)
bitrate_nx500pro_160=(0 c0f68910)
bitrate_nx500pro_170=(0 c0f62120)
bitrate_nx500pro_180=(0 c0f6ba20)
bitrate_nx500pro_190=(0 c0f65330)
bitrate_nx500pro_200=(0 c0f6eb30)
bitrate_nx500pro_210=(0 c0f68440)
bitrate_nx500pro_220=(0 c0f61c50)
bitrate_nx500pro_230=(0 c0f6b550)
bitrate_nx500pro_240=(0 c0f64e60)
bitrate_nx500pro_250=(0 c0f6e660)
bitrate_nx500pro_260=(0 c0f67f70)
bitrate_nx500pro_270=(0 c1f2170)
bitrate_nx500pro_280=(0 c1f2b00)
bitrate_nx500pro_290=(0 c1f24910)
bitrate_nx500pro_300=(0 c1f2e110)
bitrate_nx500pro_310=(0 c1f27a20)
bitrate_nx500pro_320=(0 c1f21230)
bitrate_nx500pro_400=(0 c1f2d770)
########################################################################
############ DO NOT TOUCH ##############################################
############ bitrate offset definitions ################################
############ see scripts/nx-bitrate-map.png to find out more ###########
########################################################################
nx1_pro1=(0x0 0xb40f69dc)
nx1_pro2=(0x0 0xb40f6a24)
nx1_hq1=(0x0 0xb40f683a)
nx1_hq2=(0x0 0xb40f6936)
nx1_hq3=(0x0 0xb40f6a38)
#
nx500_pro1=(0x0 0xb4095a08)
nx500_pro2=(0x0 0xb40959fe)
nx500_pro3=(0x0 0xb4095a68)
nx500_hq1=(0x0 0xb409596a)
nx500_hq2=(0x0 0xb40958f8)
nx500_hq3=(0x0 0xb4095a58)
nx500_hq4=(0x0 0xb4095928)
nx500_hq5=(0x0 0xb40959aa)
nx500_hq6=(0x0 0xb40959b2)
#
if [ $(/bin/grep ^NX500$ /etc/version.info) = "NX500" -a $(/bin/grep ^1.12$ /etc/version.info) = "1.12" ]; then
        if [ $1 = "pro1" -o $1 = "pro2" -o $1 = "pro3" ]; then
                br0=bitrate_nx500pro_$2[0]; br1=bitrate_nx500pro_$2[1]
        else
                br0=bitrate_$2[0]; br1=bitrate_$2[1]
        fi
        off0=nx500_$1[0]; off1=nx500_$1[1]
        if [[  ${!off0}>"" &&  ${!off1}>"" && ${!br0}>"" && ${!br1}>"" ]]; then
               /opt/usr/nx-ks/poker $(pgrep di-camera-app) ${!off1}:${!br1}
        fi
elif [ $(/bin/grep   ^NX1$   /etc/version.info) = "NX1" -a $(/bin/grep ^1.41$ /etc/version.info) = "1.41" ]; then
                br0=bitrate_$2[0]; br1=bitrate_$2[1]
                off0=nx1_$1[0]; off1=nx1_$1[1]
                if [[  ${!off0}>"" &&  ${!off1}>"" && ${!br0}>"" && ${!br1}>"" ]]; then
                        /opt/usr/nx-ks/poker $(pgrep di-camera-app) ${!off1}:${!br1}
                fi
fi
exit
